/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-03-30 00:13:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<style>\n");
      out.write("#team {\n");
      out.write("	vertical-align:middle;\n");
      out.write("	margin-top:40px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<footer class=\"row row-cols-5 py-5 my-5 py-5 bg-secondary\">\n");
      out.write("\n");
      out.write("	    <div class=\"col\" id=\"team\">\n");
      out.write("	      <ul class=\"nav flex-column\">\n");
      out.write("	      	<li class=\"nav-item mb-2\"><p class=\"text-center\"><a href=\"https://github.com/jamm1n1/pleaseCal\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/image/git.png\" alt=\"깃허브이미지\" style=\"width: 50px; height:auto;\"/></p></a></li>\n");
      out.write("	        <li class=\"nav-item mb-2\"><p class=\"text-center text-white\">&copy; 2022.04.04 세미프로젝트 1팀</p></li>\n");
      out.write("	      </ul>\n");
      out.write("	    </div>\n");
      out.write("\n");
      out.write("	    <div class=\"col\">\n");
      out.write("	      <p class=\"m-0 text-center text-black\"><b>김영진</b></p>\n");
      out.write("	      <ul class=\"nav flex-column\">\n");
      out.write("	        <li class=\"nav-item mb-2\"></li>\n");
      out.write("	        <li class=\"nav-item mb-2\"><p class=\"m-0 text-center text-white\">장바구니</p></li>\n");
      out.write("	        <li class=\"nav-item mb-2\"><p class=\"m-0 text-center text-white\">결제API</p></li>\n");
      out.write("	        <li class=\"nav-item mb-2\"><p class=\"m-0 text-center text-white\">주문내역</p></li>\n");
      out.write("	        \n");
      out.write("	      </ul>\n");
      out.write("	    </div>\n");
      out.write("	\n");
      out.write("	    <div class=\"col\">\n");
      out.write("	      <p class=\"m-0 text-center text-black\"><b>서제민</b></p>\n");
      out.write("	      <ul class=\"nav flex-column\">\n");
      out.write("		<li class=\"nav-item mb-2\"></li>\n");
      out.write("	        <li class=\"nav-item mb-2\"><p class=\"m-0 text-center text-white\">회원가입기능</p></li>\n");
      out.write("	        <li class=\"nav-item mb-2\"><p class=\"m-0 text-center text-white\">로그인기능</p></li>\n");
      out.write("	        <li class=\"nav-item mb-2\"><p class=\"m-0 text-center text-white\">마이페이지</p></li>\n");
      out.write("	        <li class=\"nav-item mb-2\"><p class=\"m-0 text-center text-white\">관리자페이지</p></li>\n");
      out.write("	      </ul>\n");
      out.write("	    </div>\n");
      out.write("	\n");
      out.write("	    <div class=\"col\">\n");
      out.write("	      <p class=\"m-0 text-center text-black\"><b>임찬희</b></p>\n");
      out.write("	      <ul class=\"nav flex-column\">\n");
      out.write("		<li class=\"nav-item mb-2\"></li>\n");
      out.write("	        <li class=\"nav-item mb-2\"><p class=\"m-0 text-center text-white\">Features</p></li>\n");
      out.write("	        <li class=\"nav-item mb-2\"><p class=\"m-0 text-center text-white\">Pricing</p></li>\n");
      out.write("	        <li class=\"nav-item mb-2\"><p class=\"m-0 text-center text-white\">FAQs</p></li>\n");
      out.write("	        <li class=\"nav-item mb-2\"><p class=\"m-0 text-center text-white\">About</p></li>\n");
      out.write("	      </ul>\n");
      out.write("	    </div>\n");
      out.write("	    \n");
      out.write("	    <div class=\"col\">\n");
      out.write("	      <p class=\"m-0 text-center text-black\"><b>현주아</b></p>\n");
      out.write("	      <ul class=\"nav flex-column\">\n");
      out.write("		<li class=\"nav-item mb-2\"></li>\n");
      out.write("	        <li class=\"nav-item mb-2\"><p class=\"m-0 text-center text-white\">상품</p></li>\n");
      out.write("	        <li class=\"nav-item mb-2\"><p class=\"m-0 text-center text-white\">건강계산기</p></li>\n");
      out.write("	        <li class=\"nav-item mb-2\"><p class=\"m-0 text-center text-white\">후기게시판</p></li>\n");
      out.write("	        <li class=\"nav-item mb-2\"><p class=\"m-0 text-center text-white\">전체검색</p></li>\n");
      out.write("	      </ul>\n");
      out.write("	    </div>\n");
      out.write("\n");
      out.write("    </footer>\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
