/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-03-25 00:36:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.uni.member.model.vo.Member;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.uni.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

Member loginUser = (Member) session.getAttribute("loginUser");


      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("   content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("<meta name=\"description\" content=\"\" />\n");
      out.write("<meta name=\"author\" content=\"\" />\n");
      out.write("<title>Shop Homepage - Start Bootstrap Template</title>\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jua&family=Noto+Sans+KR:wght@500&display=swap\" rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\" href=\"././resources/css/owl.carousel.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"././resources/css/owl.carousel.min.css\">\n");
      out.write("<link href=\"././resources/css/styles.css\" rel=\"stylesheet\" />\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n");
      out.write("<script src=\"./resources/js/owl.carousel.js\"></script>\n");
      out.write("<script src=\"./resources/js/owl.carousel.min.js\"></script>\n");
      out.write("\n");
      out.write(" <style>\n");
      out.write("\n");
      out.write(" * {\n");
      out.write(" 	font-family: 'Noto Sans KR', sans-serif;\n");
      out.write(" }\n");
      out.write(" </style>\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- Navigation-->\n");
      out.write("\n");
      out.write("\n");
      out.write("      <nav class=\"navbar navbar-expand-lg navbar-light fixed-top bg-light\">\n");
      out.write("          <div class=\"container px-4 px-lg-6\">\n");
      out.write("              <a class=\"navbar-brand\" href=\"#!\">CAL</a>\n");
      out.write("              <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"></span></button>\n");
      out.write("              <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("                  <ul class=\"navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4\">\n");
      out.write("                      <li class=\"nav-item\"><a class=\"nav-link active\" aria-current=\"page\" href=\"");
      out.print(request.getContextPath() );
      out.write("\">Home</a></li>\n");
      out.write("                      </li>\n");
      out.write("                      <li class=\"nav-item dropdown\">\n");
      out.write("                          <a class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">상품</a>\n");
      out.write("                          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/productlistForm.do\">모든상품</a></li>\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/selectProductListForm.do?category=2\">단백질보충제</a></li>\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/selectProductListForm.do?category=1\">닭가슴살</a></li>\n");
      out.write("                              <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/selectProductListForm.do?category=3\">도시락</a></li>\n");
      out.write("                          </ul>\n");
      out.write("                      </li>\n");
      out.write("                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(request.getContextPath() );
      out.write("/noticeList.do\">공지사항</a>\n");
      out.write("                         	<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(request.getContextPath() );
      out.write("/boardList.do\">Q&A</a>\n");
      out.write("                      </li>\n");
      out.write("                      <li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print(request.getContextPath() );
      out.write("/healthInfo.do\">건강계산기</a>\n");
      out.write("\n");
      out.write("               </ul>\n");
      out.write("               <form class=\"searching\" action=\"");
      out.print(request.getContextPath() );
      out.write("/searchProduct.do\">\n");
      out.write("            	 <input class=\"form-control\" type=\"text\" placeholder=\"전체검색\" name=\"search\">\n");
      out.write("           	   </form>  &nbsp; &nbsp;\n");
      out.write("             \n");
      out.write("             <div>\n");
      out.write("              \n");
      out.write("               <button class=\"btn btn-outline-dark\" type=\"button\" onClick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/cartList.do'\">\n");
      out.write("                  <i class=\"bi-cart-fill me-1\"></i> Cart <span\n");
      out.write("                     class=\"badge bg-dark text-white ms-1 rounded-pill\">0</span>\n");
      out.write("               </button>&nbsp;\n");
      out.write("\n");
      out.write("                  </div>\n");
      out.write("            ");
 if (loginUser == null) { 
      out.write("\n");
      out.write("\n");
      out.write("                  <i class=\"fa-thin fa-people-roof\"></i>\n");
      out.write("                  <input class=\"btn btn-outline-dark\" id=\"manager\" type=\"button\" value=\"로그인\" onClick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/LoginPage.do'\"><span\n");
      out.write("                     class=\"badge bg-dark text-white ms-1 rounded-pill\"></span>\n");
      out.write("                           \n");
      out.write("               ");
 } else { 
      out.write("\n");
      out.write("   \n");
      out.write("               ");
 if (loginUser != null && loginUser.getUserId().equals("admin")) { 
      out.write("\n");
      out.write("   \n");
      out.write("\n");
      out.write("                    <i class=\"fa-thin fa-people-roof\"></i>\n");
      out.write("                  	<input class=\"btn btn-outline-dark\" id=\"manager\" type=\"button\" value=\"관리자페이지\" onClick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/managerPage.do'\"><span\n");
      out.write("                     class=\"badge bg-dark text-white ms-1 rounded-pill\"></span>&nbsp;\n");
      out.write("\n");
      out.write("                  \n");
      out.write("                   <i class=\"fa-thin fa-people-roof\"></i>\n");
      out.write("                   <input class=\"btn btn-outline-dark\" id=\"manager\" type=\"button\" value=\"로그아웃\" onClick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/logoutMember.do'\"><span\n");
      out.write("                     class=\"badge bg-dark text-white ms-1 rounded-pill\"></span>\n");
      out.write("\n");
      out.write("               ");
 } else { 
      out.write("\n");
      out.write("   \n");
      out.write("                  \n");
      out.write(" 				<div id=\"userInfo\">\n");
      out.write("					<i class=\"fa-thin fa-people-roof\"></i>\n");
      out.write("                    <input class=\"btn btn-outline-dark\" id=\"manager\" type=\"button\" value=\"마이페이지\" onClick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/mypageMember.do'\"><span\n");
      out.write("                     class=\"badge bg-dark text-white ms-1 rounded-pill\"></span>\n");
      out.write("                     \n");
      out.write("                    <i class=\"fa-thin fa-people-roof\"></i>\n");
      out.write("                   <input class=\"btn btn-outline-dark\" id=\"manager\" type=\"button\" value=\"로그아웃\" onClick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/logoutMember.do'\"><span\n");
      out.write("                     class=\"badge bg-dark text-white ms-1 rounded-pill\"></span>\n");
      out.write("                     <b style=\"color: blue;\">");
      out.print(loginUser.getUserName());
      out.write(" 님 </b> 어서오세요.\n");
      out.write("				</div>\n");
      out.write("                  \n");
      out.write("                  ");
}
      out.write("\n");
      out.write("               ");
}
      out.write("\n");
      out.write("               \n");
      out.write("            \n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("   </nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
