/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-03-30 00:13:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.cart;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class paymentResult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write(".date {\r\n");
      out.write("  	text-align: right;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   * {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	table {\r\n");
      out.write("	    border-collapse: collapse;\r\n");
      out.write("	    border-spacing: 0;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	tbody {\r\n");
      out.write("    display: table-row-group;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    border-color: inherit;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("  .contents-cart {\r\n");
      out.write("      position: relative;\r\n");
      out.write("    visibility: hidden;\r\n");
      out.write("    width: 1000px;\r\n");
      out.write("    border: 1px solid #e0e0e0;\r\n");
      out.write("    margin: 0 auto 70px;\r\n");
      out.write("    padding: 40px 39px;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .cart-title {\r\n");
      out.write("        clear: both;\r\n");
      out.write("    height: 45px;\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("    padding-bottom: 32px;\r\n");
      out.write("    font-size: 30px\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    .cartTable{\r\n");
      out.write("    width: 898px;\r\n");
      out.write("    border-top: 0;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #cartTable-sku td.cart-deal-item__image {\r\n");
      out.write("    padding-right: 15px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#cartTable-sku td.product-box {\r\n");
      out.write("    padding-left: 0;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("    colgroup{\r\n");
      out.write("    display: table-column-group;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    table {\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    border-spacing: 0;\r\n");
      out.write("    text-indent: initial;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	body, input, textarea, select, button, table {\r\n");
      out.write("    font-family: sans-serif;\r\n");
      out.write("    font-size: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	a, blockquote, body, button, dd, div, dl, dt, fieldset, form, h1, h2, h3, h4, h5, h6, input, li, ol, p, pre, select, span, td, textarea, th, ul {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    color: #111;\r\n");
      out.write("    font-family: Dotum,\\\\B3CB\\C6C0,sans-serif;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cartTable .head {\r\n");
      out.write("    border-top: 1px solid #ddd;\r\n");
      out.write("    border-bottom: 1px solid #ddd;\r\n");
      out.write("    background: lightyellow;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cartTable th {\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	.product-name-part {\r\n");
      out.write("    border-bottom: 1px solid #e2e5e7;\r\n");
      out.write("    padding-bottom: 5px;\r\n");
      out.write("    letter-spacing: -1px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.cart-deal-item td.product-box {\r\n");
      out.write("	    padding: 10px 5px 10px 15px;\r\n");
      out.write("	    text-align: left;\r\n");
      out.write("	    vertical-align: top;\r\n");
      out.write("	    z-index: 100;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cartTable td {\r\n");
      out.write("    border-bottom: 1px solid #ddd;\r\n");
      out.write("    line-height: 35px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.option-price-part {\r\n");
      out.write("    float: right;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    line-height: 24px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cart-deal-item td.product-box {\r\n");
      out.write("    padding: 10px 5px 10px 15px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    z-index: 100;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("    .cart-deal-item td:nth-child(2) {\r\n");
      out.write("    width: 350px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cart-deal-item td:nth-child(3) {\r\n");
      out.write("    width: 60px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cart-deal-item td:nth-child(4) {\r\n");
      out.write("    width: 60px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cart-deal-item .unit-total-price {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    line-height: normal;\r\n");
      out.write("    border-left: 1px solid #ddd;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    color: #888;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cart-deal-item td {\r\n");
      out.write("    padding: 10px 0;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.delivery-fee {\r\n");
      out.write("    border-left: 1px solid #ddd;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    color: #888;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.bundle-price-total td {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    padding: 20px 35px 16px 0;\r\n");
      out.write("    background: lightyellow;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    line-height: 29px;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	a, blockquote, body, button, dd, div, dl, dt, fieldset, form, h1, h2, h3, h4, h5, h6, input, li, ol, p, pre, select, span, td, textarea, th, ul {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    color: #111;\r\n");
      out.write("    font-family: Dotum,\\\\B3CB\\C6C0,sans-serif;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.bundle-price-total .global-total-price-area, .bundle-price-total .rocket-fresh-total-price-area, .bundle-price-total .rocket-install-total-price-area, .bundle-price-total .rocket-total-price-area {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.sr-only {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    height: 1px;\r\n");
      out.write("    width: 1px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    clip: rect(1px 1px 1px 1px);\r\n");
      out.write("    clip: rect(1px,1px,1px,1px);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.bundle-price-total .number {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    font: normal 15px/15px tahoma;\r\n");
      out.write("    color: #111;\r\n");
      out.write("    vertical-align: 0;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.symbol-minus, .symbol-plus {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: 18px;\r\n");
      out.write("    height: 18px;\r\n");
      out.write("    margin: 0 8px;\r\n");
      out.write("    vertical-align: -5px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.symbol-plus {\r\n");
      out.write("    background: url(//img1a.coupangcdn.com/image/order/mathematics-symbol.png) no-repeat;\r\n");
      out.write("    background-position: 0 0;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.symbol-equal, .symbol-plus1 {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: 18px;\r\n");
      out.write("    height: 18px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.symbol-equal {\r\n");
      out.write("    margin: 0 8px;\r\n");
      out.write("    background: url(//img1a.coupangcdn.com/image/order/mathematics-symbol.png) no-repeat;\r\n");
      out.write("    vertical-align: -5px;\r\n");
      out.write("    background-position: -36px 0;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.bundle-price-total .total-order-price.number {\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cart-total-price {\r\n");
      out.write("    clear: both;\r\n");
      out.write("    border: 4px solid #c8c8c8;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cart-total-price__inner {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cart-total-price .price-area {\r\n");
      out.write("    padding: 20px 15px 18px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    line-height: 17px;\r\n");
      out.write("    color: #555;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	 \r\n");
      out.write("	 .sr-only {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    height: 1px;\r\n");
      out.write("    width: 1px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    clip: rect(1px 1px 1px 1px);\r\n");
      out.write("    clip: rect(1px,1px,1px,1px);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.symbol-plus1 {\r\n");
      out.write("    margin: 0 11px 0 10px;\r\n");
      out.write("    vertical-align: -4px;\r\n");
      out.write("    background: url(//img1a.coupangcdn.com/image/www/newBuy/img_plus_2.gif) no-repeat;\r\n");
      out.write("	}\r\n");
      out.write("	 \r\n");
      out.write("	.symbol-equal, .symbol-plus1 {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: 18px;\r\n");
      out.write("    height: 18px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.cart-total-price em {\r\n");
      out.write("	    padding: 0 4px 0 5px;\r\n");
      out.write("	    font: 700 17px/17px tahoma;\r\n");
      out.write("	    color: #111;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.symbol-equal1 {\r\n");
      out.write("	    background: url(//img1a.coupangcdn.com/image/www/newBuy/img_equals_2.gif) no-repeat;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.symbol-equal1, .symbol-minus1 {\r\n");
      out.write("	    display: inline-block;\r\n");
      out.write("	    width: 18px;\r\n");
      out.write("	    height: 18px;\r\n");
      out.write("	    margin: 0 11px 0 10px;\r\n");
      out.write("	    vertical-align: -4px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.cart-total-price .final-order-price {\r\n");
      out.write("	    color: #ea0000;\r\n");
      out.write("	    font-size: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.faraway-notice {\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    padding: 12px 0 9px;\r\n");
      out.write("    background: #fafafa;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    color: #555;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    visibility: hidden;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.goPayment, .goShopping {\r\n");
      out.write("    font-size: 22px;\r\n");
      out.write("    font-weight: 1000;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    line-height: 18px;\r\n");
      out.write("    border: 2px solid lightgray;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    padding: 22px 0 19px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.goShopping {\r\n");
      out.write("    background: white;\r\n");
      out.write("    color: skyblue;\r\n");
      out.write("    margin-right: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.goPayment {\r\n");
      out.write("    background: skyblue;\r\n");
      out.write("    color: white;\r\n");
      out.write("    \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.delete-option {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: 18px;\r\n");
      out.write("    height: 18px;\r\n");
      out.write("    margin-top: 3px;\r\n");
      out.write("    background: url(//img1a.coupangcdn.com/image/cart/generalCart/cart_sprite_170201.png) -114px 0 no-repeat;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    z-index: 120;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.option-price-part {\r\n");
      out.write("    float: right;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    line-height: 24px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.unit-cost {\r\n");
      out.write("	    color: #888;\r\n");
      out.write("	    letter-spacing: 0;\r\n");
      out.write("	    vertical-align: top;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.customer__h2 {\r\n");
      out.write("    padding-left: 2px;\r\n");
      out.write("    margin-bottom: 8px;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    color: #333;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.customer__table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border-top: 2px solid #cecece;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.customer__col--2 {\r\n");
      out.write("	    border-bottom: 1px solid #e4e4e4;\r\n");
      out.write("	    padding: 10px 16px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.customer__col--1 {\r\n");
      out.write("    width: 120px;\r\n");
      out.write("    border: solid #e4e4e4;\r\n");
      out.write("    border-width: 0 1px 1px 0;\r\n");
      out.write("    padding: 7px 10px 7px 15px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("    background: #f4f4f4;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.customer__col--2 {\r\n");
      out.write("    border-bottom: 1px solid #e4e4e4;\r\n");
      out.write("    padding: 10px 16px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.page-pc.page-order input[type=password], .page-pc.page-order input[type=tel], .page-pc.page-order input[type=text] {\r\n");
      out.write("	    height: 22px;\r\n");
      out.write("	    padding: 0 0 0 5px;\r\n");
      out.write("	    border: 1px solid #ddd;\r\n");
      out.write("	    font-size: 12px;\r\n");
      out.write("	    color: #333;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.customer__root {\r\n");
      out.write("    margin-top: 40px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#product-list-amount{\r\n");
      out.write("	\r\n");
      out.write("		font-size: 15px;\r\n");
      out.write("\r\n");
      out.write("		color: cadetblue;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.delivery-address__caption-header {\r\n");
      out.write("    padding-left: 2px;\r\n");
      out.write("    margin: 30px 0 8px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.delivery-address {\r\n");
      out.write("    border-top: 2px solid #cecece;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.delivery-address__th {\r\n");
      out.write("    border-right: 1px solid #e4e4e4;\r\n");
      out.write("    border-bottom: 1px solid #e4e4e4;\r\n");
      out.write("    padding: 10px 10px 7px 15px;\r\n");
      out.write("    width: 120px;\r\n");
      out.write("    background-color: #f4f4f4;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.delivery-address__td--name {\r\n");
      out.write("    padding-top: 12.5px;\r\n");
      out.write("    padding-bottom: 12.5px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.delivery-address__td {\r\n");
      out.write("    border-bottom: 1px solid #e4e4e4;\r\n");
      out.write("    padding: 10px 0 10px 16px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	body, dd, div, dl, dt, fieldset, form, h1, h2, h3, h4, h5, h6, li, ol, pre, ul {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    font-family: \"돋움\",Dotum,sans-serif;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.delivery-request-message__container {\r\n");
      out.write("    border-top: 1px solid #e4e4e4;\r\n");
      out.write("    border-left: 1px solid #f4f4f4;\r\n");
      out.write("    border-bottom: 1px solid #e4e4e4;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.delivery-request-message {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	tbody {\r\n");
      out.write("    display: table-row-group;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    border-color: inherit;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.delivery-request-message__th {\r\n");
      out.write("    padding: 7px 10px 7px 15px;\r\n");
      out.write("    border-right: 1px solid #e4e4e4;\r\n");
      out.write("    width: 103px;\r\n");
      out.write("    background-color: #f4f4f4;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.delivery-request-message__td--name {\r\n");
      out.write("    padding-top: 10px;\r\n");
      out.write("    padding-bottom: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.delivery-request-message__td {\r\n");
      out.write("    padding: 10px 0 10px 16px;\r\n");
      out.write("    border-left: 1px solid #e4e4e4;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div[data-ajax-view=box] {\r\n");
      out.write("    position: relative;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.bundle-info__retail {\r\n");
      out.write("    margin-top: 8px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.page-pc .bundle-info__pdd-group-title {\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.bundle-info__pdd-group-title {\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    margin-bottom: 9px;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    line-height: 21px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.order-buttons, .summary-area {\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    position: relative;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/menu.jsp", out, false);
      out.write("\r\n");
      out.write("	<br><br><br><br><br><br><br>\r\n");
      out.write("	<div>\r\n");
      out.write("		<p> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("  	<div class=\"order-buttons\">p\r\n");
      out.write("	 \r\n");
      out.write("		<a id=\"continueShoopingBtn\" class=\"goShopping logging\" href=\"");
      out.print(request.getContextPath());
      out.write("\">쇼핑 계속 하기</a>\r\n");
      out.write("		<a id=\"continueShoopingBtn\" class=\"goShopping logging\" href=\"");
      out.print(request.getContextPath());
      out.write("/myOrderList.do\">주문내역으로 이동</a>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
