/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-03-30 04:45:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class newface_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("   \n");
      out.write("  \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<style>\n");
      out.write("input{\n");
      out.write("width:500px;\n");
      out.write("height:50px;\n");
      out.write("}\n");
      out.write("#waddress{\n");
      out.write("width:70px;\n");
      out.write("height:50px;\n");
      out.write("}\n");
      out.write("body{\n");
      out.write("background-image:url('https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2F20150404_201%2Fbbilla_1428082120293qFxQp_JPEG%2F%25C7%25CF%25B3%25AA%25BE%25B2%25B9%25D9%25C5%25C1%25C8%25AD%25B8%25E9_05_1920x1080_20150402-01.jpg&type=a340')\n");
      out.write("}\n");
      out.write("#joinBtn{\n");
      out.write("width: 120px;\n");
      out.write("background-color : #64FE2E;\n");
      out.write("color : blue;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"outer\">\n");
      out.write("		<br>\n");
      out.write("		\n");
      out.write("		<h2 align=\"center\">계정만들기</h2>\n");
      out.write("		\n");
      out.write("		<form id=\"enrollForm\" action=\"");
      out.print(request.getContextPath() );
      out.write("/insertMember.do\" method=\"post\" onsubmit=\"return joinValidate();\">\n");
      out.write("			<table align=\"center\" width=\"750px\">\n");
      out.write("				<tr>	\n");
      out.write("				<td>아이디</td>			\n");
      out.write("					<td><input type=\"text\"  name=\"userId\"  placeholder=\"아이디를 입력하세요\" width=\"300px\" required></td>\n");
      out.write("					<td>\n");
      out.write("						<button type=\"button\" id=\"idCheckBtn\" onclick=\"checkId();\">아이디중복체크</button>\n");
      out.write("					</td>\n");
      out.write("						\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>	\n");
      out.write("				<td>비밀번호</td>					\n");
      out.write("					<td><input type=\"password\"  name=\"userPwd\" placeholder=\"비밀번호를 입력하세요\" required></td>\n");
      out.write("					<td></td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>	\n");
      out.write("				<td>비밀번호 확인</td>				\n");
      out.write("					<td><input type=\"password\"  name=\"checkPwd\" placeholder=\"비밀번호 확인!\" required></td>\n");
      out.write("					<td><label id = \"pwdResult\"></label></td>\n");
      out.write("				</tr>	\n");
      out.write("				<tr>	\n");
      out.write("				<td>이름</td>			\n");
      out.write("					<td><input type=\"text\"  name=\"userName\" placeholder=\"이름을 입력하세요\" required></td>\n");
      out.write("					<td></td>\n");
      out.write("				</tr>\n");
      out.write("				\n");
      out.write("				<tr>\n");
      out.write("					<td>주소</td>	\n");
      out.write("					<td><input type=\"text\" name=\"address\" id=\"address\" placeholder=\"주소를 입력하세요\" required></td>\n");
      out.write("					<td><input type=\"button\" id=\"waddress\" value =\"주소입력!\" ></input></td>\n");
      out.write("		\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td>전화번호(-포함)</td>	\n");
      out.write("					<td><input type=\"tel\" maxlength=\"13\" name=\"phone\" placeholder=\"전화번호 입력해주세요(-입력)010-1234-5678\" oninput=\"Hyphen(this)\" required></td>\n");
      out.write("					<td></td>\n");
      out.write("				</tr>	\n");
      out.write("				\n");
      out.write("			</table>\n");
      out.write("			<br>\n");
      out.write("			<div class=\"btns\" align=\"center\">				\n");
      out.write("				<button type=\"submit\" id=\"joinBtn\" onclick=\"insert()\" hidden >가입하기</button>\n");
      out.write("			\n");
      out.write("				\n");
      out.write("			</div>\n");
      out.write("		</form>\n");
      out.write("	\n");
      out.write("	</div>\n");
      out.write("	<script>\n");
      out.write("	   window.onload = function(){\n");
      out.write("    document.getElementById(\"waddress\").addEventListener(\"click\", function(){ \n");
      out.write("       new daum.Postcode({\n");
      out.write("       oncomplete: function(data) { //선택시 입력값 세팅\n");
      out.write("           document.getElementById(\"address\").value = data.address; // 주소 넣기        \n");
      out.write("       }\n");
      out.write("   }).open();\n");
      out.write("});\n");
      out.write("}\n");
      out.write("	\n");
      out.write("	   function joinValidate(){\n");
      out.write("			\n");
      out.write("	\n");
      out.write("		if($(\"#enrollForm input[name=userPwd]\").val() != $(\"#enrollForm input[name=checkPwd]\").val()){\n");
      out.write("			$(\"#pwdResult\").text(\"비밀번호가달라요\").css(\"color\", \"red\");\n");
      out.write("			return false;		\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("				\n");
      out.write("		window.alert(\"회원가입 성공 환영해요(ノ・∀・)ノ\");\n");
      out.write("		 return true;\n");
      out.write("		\n");
      out.write("		\n");
      out.write("	}\n");
      out.write("	function checkId(){\n");
      out.write("		var userId = $(\"#newFace input[name=userId]\");\n");
      out.write("		\n");
      out.write("		if(userId.val() ==\"\"){\n");
      out.write("			alert(\"아이디를 입력해주세요\")\n");
      out.write("			return false;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		$.ajax({\n");
      out.write("			url:\"idCheck.do\",\n");
      out.write("			type:\"post\",\n");
      out.write("			data:{userId:userId.val()},\n");
      out.write("			success:function(result){\n");
      out.write("				if(result ==\"fail\"){\n");
      out.write("					alert(\"사용불가한 아이디입니다.\");\n");
      out.write("					userId.focus();\n");
      out.write("					\n");
      out.write("				}else{\n");
      out.write("					if(confirm(\"사용가능한 아이디입니다.\")){\n");
      out.write("						userId.attr(\"readonly\",\"true\");\n");
      out.write("						$(\"#joinBtn\").removeAttr(\"hidden\");\n");
      out.write("					}else{\n");
      out.write("						userId.focus();\n");
      out.write("					}\n");
      out.write("				}\n");
      out.write("			},\n");
      out.write("			error:function(){\n");
      out.write("				console.log(\"서버통신실패\")\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	\n");
      out.write("	const Hyphen = (target) => {\n");
      out.write("		 target.value = target.value\n");
      out.write("		   .replace(/[^0-9]/g, '') //전체에서  0~9사이에 아무 숫자 '하나'  찾음 \n");
      out.write("		  .replace(/^(\\d{0,3})(\\d{0,4})(\\d{0,4})$/g, \"$1-$2-$3\").replace(/(\\-{1,2})$/g, \"\");\n");
      out.write("		}\n");
      out.write("	</script>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
